name: Emoji Manager

on:
  push:
    paths:
      - 'emojis/**'
  workflow_dispatch:

jobs:
  emoji-replacement:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run emoji manager
        run: |
          cd emojis
          python emoji_manager.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update emoji output'
          branch: ${{ github.ref }}
